### ISSUE TITLE
 does not work with Blender 2.9x

### ISSUE THREAD

**Issue by lukas-blecher** [lukas-blecher/AutoMask#10]
Installing throws dependency errors.
#9

**Comment by jcnwholland** [comment]
Hi I tried your suggestion, following output: Thxn for taking the time.

Regarding the python requirements: do you need to assign them to a program?

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\blender-2.80rc1-windows64\blender-2.80rc1-windows64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\automask.py", line 12, in <module>
    from mask_spline import *
  File "C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\mask_spline.py", line 5, in <module>
    from skimage import measure
  File "C:\Program Files\Python37\Lib\site-packages\skimage\__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "C:\Program Files\Python37\Lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "C:\Program Files\Python37\Lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed: The specified module could not be found.

**Comment by lukas-blecher** [comment]
Hello,
this has nothing to do with the incompatibility with Blender 2.9. Open a new issue for that.
Check out existing answers to your problem since it has nothing to do with the code in this repository:
https://github.com/scikit-image/scikit-image/issues/4780
https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found/20230455

**Comment by jcnwholland** [comment]
Ok, have it running on blender 2.9 though..
"python -m pip install msvc-runtime" did the trick, happy to share my installing workflow.. could help allot of users, let me  know

**Comment by lukas-blecher** [comment]
Thank you for the contribution. 
I'm still getting the same error as described in #9 
What python version are you using?

**Comment by Shk-aftab** [comment]
**While installing automask.py addon, I am getting this error on click of Motion Tracking**

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\acer\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\automask.py", line 13, in <module>
    from mask_spline import *
ModuleNotFoundError: No module named 'mask_spline'

**Comment by MaximStale** [comment]
Any news?
